#!/bin/bash

repo="$(iai repo)" || exit
cd "$repo" || exit

node test/exports.js || exit

while read directory
do
  reference="${directory/"test/cases"/./cases}"
  node test/cases.js "$reference" || exit
  node test/from.js "$directory" || exit
done < <(find test/cases -mindepth 1 -maxdepth 1 -type d )

{
  echo "TEST standard --fix"
  standard --fix
  code=$?
  (( $code )) \
    && echo "FAIL standard linter reported errors" \
    || echo "PASS standard linter did not report errors"
  echo "CODE $code"
  exit $code
}
