#!/bin/bash

repo="$(iai repo)" || exit
cd "$repo" || exit

node test/exports.js || exit

find test/cases -mindepth 1 -maxdepth 1 -type d | while read directory
do
  node test/cases.js ${directory/"test/cases"/./cases} || exit
done

{
  echo "TEST standard --fix"
  standard --fix
  code=$?
  (( $code )) \
    && echo "FAIL standard linter reported errors" \
    || echo "PASS standard linter did not report errors"
  echo "CODE $code"
  exit $code
}
